// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package nproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RPCError - -32600]
	_ = x[RPCSpecInvalid - -32601]
	_ = x[RPCSvcNotFound - -32602]
	_ = x[RPCMethodNotFound - -32603]
	_ = x[RPCRequestEncodeError - -32604]
	_ = x[RPCRequestDecodeError - -32605]
	_ = x[RPCResponseEncodeError - -32606]
	_ = x[RPCResponseDecodeError - -32607]
}

const _ErrorCode_name = "RPCResponseDecodeErrorRPCResponseEncodeErrorRPCRequestDecodeErrorRPCRequestEncodeErrorRPCMethodNotFoundRPCSvcNotFoundRPCSpecInvalidRPCError"

var _ErrorCode_index = [...]uint8{0, 22, 44, 65, 86, 103, 117, 131, 139}

func (i ErrorCode) String() string {
	i -= -32607
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+-32607), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
