// Code generated by "stringer -type=RPCErrorCode"; DO NOT EDIT.

package rpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownError - -32600]
	_ = x[SvcNotFound - -32601]
	_ = x[MethodNotFound - -32602]
	_ = x[EncodeRequestError - -32603]
	_ = x[DecodeRequestError - -32604]
	_ = x[EncodeResponseError - -32605]
	_ = x[DecodeResponseError - -32606]
}

const _RPCErrorCode_name = "DecodeResponseErrorEncodeResponseErrorDecodeRequestErrorEncodeRequestErrorMethodNotFoundSvcNotFoundUnknownError"

var _RPCErrorCode_index = [...]uint8{0, 19, 38, 56, 74, 88, 99, 111}

func (i RPCErrorCode) String() string {
	i -= -32606
	if i < 0 || i >= RPCErrorCode(len(_RPCErrorCode_index)-1) {
		return "RPCErrorCode(" + strconv.FormatInt(int64(i+-32606), 10) + ")"
	}
	return _RPCErrorCode_name[_RPCErrorCode_index[i]:_RPCErrorCode_index[i+1]]
}
