// Code generated by protoc-gen-go. DO NOT EDIT.
// source: md.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MetaDataKV is a kv pair of meta data.
// Use `repeated MetaDataKV` to represent a meta data dict since map value
// can't be repeated type.
// See: https://stackoverflow.com/questions/38886789/protobuf3-how-to-describe-map-of-repeated-string
type MetaDataKV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaDataKV) Reset()         { *m = MetaDataKV{} }
func (m *MetaDataKV) String() string { return proto.CompactTextString(m) }
func (*MetaDataKV) ProtoMessage()    {}
func (*MetaDataKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e149d9fdc447d0, []int{0}
}

func (m *MetaDataKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDataKV.Unmarshal(m, b)
}
func (m *MetaDataKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDataKV.Marshal(b, m, deterministic)
}
func (m *MetaDataKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDataKV.Merge(m, src)
}
func (m *MetaDataKV) XXX_Size() int {
	return xxx_messageInfo_MetaDataKV.Size(m)
}
func (m *MetaDataKV) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDataKV.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDataKV proto.InternalMessageInfo

func (m *MetaDataKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetaDataKV) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*MetaDataKV)(nil), "nproto.pb.md.MetaDataKV")
}

func init() { proto.RegisterFile("md.proto", fileDescriptor_e0e149d9fdc447d0) }

var fileDescriptor_e0e149d9fdc447d0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x4d, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0x03, 0xd3, 0x7a, 0x05, 0x49, 0x7a, 0xb9, 0x29, 0x4a,
	0x66, 0x5c, 0x5c, 0xbe, 0xa9, 0x25, 0x89, 0x2e, 0x89, 0x25, 0x89, 0xde, 0x61, 0x42, 0x02, 0x5c,
	0xcc, 0xd9, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x18, 0x17,
	0x5b, 0x59, 0x62, 0x4e, 0x69, 0x6a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x4f, 0x10, 0x94, 0xe7,
	0xa4, 0x19, 0xa5, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x51,
	0x9a, 0x98, 0x97, 0x9e, 0x55, 0x9a, 0x57, 0x9e, 0x9a, 0xa7, 0x0f, 0x31, 0x1e, 0x46, 0x15, 0x24,
	0x25, 0xb1, 0x81, 0x59, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xdc, 0x57, 0xb8, 0x83,
	0x00, 0x00, 0x00,
}
