// Code generated by protoc-gen-go. DO NOT EDIT.
// source: npmsg.proto

package pb // import "github.com/huangjunwen/nproto/nproto/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MsgPayload is the payload of a message encoded by protobuf.
type MsgPayload struct {
	// MsgData is serialized message data.
	MsgData []byte `protobuf:"bytes,1,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	// MetaData dict.
	MetaData             []*MetaDataKV `protobuf:"bytes,2,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgPayload) Reset()         { *m = MsgPayload{} }
func (m *MsgPayload) String() string { return proto.CompactTextString(m) }
func (*MsgPayload) ProtoMessage()    {}
func (*MsgPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_npmsg_ca94139e24c19cb0, []int{0}
}
func (m *MsgPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPayload.Unmarshal(m, b)
}
func (m *MsgPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPayload.Marshal(b, m, deterministic)
}
func (dst *MsgPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayload.Merge(dst, src)
}
func (m *MsgPayload) XXX_Size() int {
	return xxx_messageInfo_MsgPayload.Size(m)
}
func (m *MsgPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayload.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayload proto.InternalMessageInfo

func (m *MsgPayload) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *MsgPayload) GetMetaData() []*MetaDataKV {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgPayload)(nil), "nproto.pb.npmsg.MsgPayload")
}

func init() { proto.RegisterFile("npmsg.proto", fileDescriptor_npmsg_ca94139e24c19cb0) }

var fileDescriptor_npmsg_ca94139e24c19cb0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2b, 0xc8, 0x2d,
	0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcf, 0x03, 0xd3, 0x7a, 0x05, 0x49, 0x7a,
	0x60, 0x61, 0x29, 0x8e, 0xdc, 0x14, 0x88, 0x94, 0x52, 0x1c, 0x17, 0x97, 0x6f, 0x71, 0x7a, 0x40,
	0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a, 0x90, 0x24, 0x17, 0x47, 0x6e, 0x71, 0x7a, 0x7c, 0x4a, 0x62,
	0x49, 0xa2, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x7b, 0x6e, 0x71, 0xba, 0x4b, 0x62, 0x49,
	0xa2, 0x90, 0x29, 0x17, 0x67, 0x6e, 0x6a, 0x49, 0x22, 0x44, 0x8e, 0x49, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x42, 0x0f, 0x61, 0x6e, 0x6e, 0x8a, 0x9e, 0x6f, 0x6a, 0x49, 0x22, 0x48, 0xa9, 0x77, 0x58,
	0x10, 0x47, 0x2e, 0x94, 0xed, 0xa4, 0x19, 0xa5, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97,
	0x9c, 0x9f, 0xab, 0x9f, 0x51, 0x9a, 0x98, 0x97, 0x9e, 0x55, 0x9a, 0x57, 0x9e, 0x9a, 0xa7, 0x0f,
	0xd1, 0x0b, 0xa3, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x56, 0x7d, 0x45, 0xfe, 0xbb, 0x00, 0x00, 0x00,
}
