// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RPCRequest is request of a RPC call encoded by protobuf.
type RPCRequest struct {
	// Param is protobuf encoded param.
	Param []byte `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	// MetaData dict.
	MetaData []*MetaDataKV `protobuf:"bytes,2,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// Timeout is timeout in nanoseconds. Use int64 instead of wkt's duration to avoid an extra pointer.
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (m *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(m, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

func (m *RPCRequest) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *RPCRequest) GetMetaData() []*MetaDataKV {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *RPCRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// Reply is reply of a RPC call encoded by protobuf.
type RPCReply struct {
	// Result is protobuf encoded result.
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Error is the error result of this rpc.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCReply) Reset()         { *m = RPCReply{} }
func (m *RPCReply) String() string { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()    {}
func (*RPCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *RPCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCReply.Unmarshal(m, b)
}
func (m *RPCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCReply.Marshal(b, m, deterministic)
}
func (m *RPCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCReply.Merge(m, src)
}
func (m *RPCReply) XXX_Size() int {
	return xxx_messageInfo_RPCReply.Size(m)
}
func (m *RPCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCReply.DiscardUnknown(m)
}

var xxx_messageInfo_RPCReply proto.InternalMessageInfo

func (m *RPCReply) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RPCReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "nproto.pb.rpc.RPCRequest")
	proto.RegisterType((*RPCReply)(nil), "nproto.pb.rpc.RPCReply")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xbf, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xc9, 0x05, 0xcf, 0x64, 0xd4, 0x66, 0x11, 0x59, 0xac, 0xc2, 0x35, 0xc6, 0x66, 0x0f,
	0x14, 0xc1, 0x5a, 0xed, 0x44, 0x90, 0x2d, 0x2c, 0x6c, 0x64, 0x92, 0x0c, 0x77, 0x27, 0xb7, 0x3f,
	0x9c, 0xcc, 0x22, 0xfe, 0xf7, 0x62, 0x36, 0x87, 0xd5, 0x7b, 0x1f, 0x03, 0xf3, 0x3e, 0xa8, 0x39,
	0xf6, 0x26, 0x72, 0x90, 0xa0, 0xce, 0xfc, 0x94, 0x26, 0x76, 0x86, 0x63, 0x7f, 0x59, 0xb9, 0x21,
	0x1f, 0x56, 0x23, 0x80, 0x7d, 0x7d, 0xb4, 0xf4, 0x95, 0x68, 0x14, 0x75, 0x0e, 0x47, 0x11, 0x19,
	0x9d, 0x2e, 0x9a, 0xa2, 0x3d, 0xb5, 0x19, 0xd4, 0x1d, 0xd4, 0x8e, 0x04, 0x3f, 0x06, 0x14, 0xd4,
	0x8b, 0xa6, 0x6c, 0x4f, 0x6e, 0xb4, 0xf9, 0x7f, 0xe8, 0x06, 0xf3, 0x42, 0x82, 0x4f, 0x28, 0xf8,
	0xfc, 0x66, 0x2b, 0x37, 0x77, 0xa5, 0xe1, 0x58, 0x76, 0x8e, 0x42, 0x12, 0x5d, 0x36, 0x45, 0x5b,
	0xda, 0x03, 0xae, 0xee, 0xa1, 0x9a, 0x46, 0xe3, 0xfe, 0x47, 0x5d, 0xc0, 0x92, 0x69, 0x4c, 0x7b,
	0x99, 0x37, 0x67, 0xfa, 0x53, 0x21, 0xe6, 0xc0, 0x7a, 0xd1, 0x14, 0x6d, 0x6d, 0x33, 0x3c, 0x5c,
	0xbf, 0x5f, 0x6d, 0x76, 0xb2, 0x4d, 0x9d, 0xe9, 0x83, 0x5b, 0x6f, 0x13, 0xfa, 0xcd, 0x67, 0xf2,
	0xdf, 0xe4, 0xd7, 0xd9, 0xe7, 0x10, 0xb1, 0xeb, 0x96, 0x53, 0xbb, 0xfd, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x15, 0xd8, 0x4f, 0x63, 0x06, 0x01, 0x00, 0x00,
}
