// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbenc.proto

package enc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PBPayload struct {
	// Msg is protobuf encoded message.
	Msg []byte `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	// Passthru is an optional dict carrying context values.
	Passthru             map[string]string `protobuf:"bytes,2,rep,name=passthru,proto3" json:"passthru,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PBPayload) Reset()         { *m = PBPayload{} }
func (m *PBPayload) String() string { return proto.CompactTextString(m) }
func (*PBPayload) ProtoMessage()    {}
func (*PBPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbenc_ce71d0c21be5f13a, []int{0}
}
func (m *PBPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBPayload.Unmarshal(m, b)
}
func (m *PBPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBPayload.Marshal(b, m, deterministic)
}
func (dst *PBPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBPayload.Merge(dst, src)
}
func (m *PBPayload) XXX_Size() int {
	return xxx_messageInfo_PBPayload.Size(m)
}
func (m *PBPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PBPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PBPayload proto.InternalMessageInfo

func (m *PBPayload) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *PBPayload) GetPassthru() map[string]string {
	if m != nil {
		return m.Passthru
	}
	return nil
}

func init() {
	proto.RegisterType((*PBPayload)(nil), "enc.PBPayload")
	proto.RegisterMapType((map[string]string)(nil), "enc.PBPayload.PassthruEntry")
}

func init() { proto.RegisterFile("pbenc.proto", fileDescriptor_pbenc_ce71d0c21be5f13a) }

var fileDescriptor_pbenc_ce71d0c21be5f13a = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0x4a, 0xcd,
	0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xcd, 0x4b, 0x56, 0x9a, 0xc2, 0xc8,
	0xc5, 0x19, 0xe0, 0x14, 0x90, 0x58, 0x99, 0x93, 0x9f, 0x98, 0x22, 0x24, 0xc0, 0xc5, 0xec, 0x5b,
	0x9c, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x62, 0x0a, 0x59, 0x70, 0x71, 0x14, 0x24,
	0x16, 0x17, 0x97, 0x64, 0x14, 0x95, 0x4a, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xc9, 0xe8, 0x81,
	0x8c, 0x80, 0xeb, 0xd1, 0x0b, 0x80, 0x4a, 0xbb, 0xe6, 0x95, 0x14, 0x55, 0x06, 0xc1, 0x55, 0x4b,
	0x59, 0x73, 0xf1, 0xa2, 0x48, 0x81, 0x0c, 0xcf, 0x4e, 0xad, 0x04, 0x1b, 0xce, 0x19, 0x04, 0x62,
	0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x81, 0xc5, 0x20, 0x1c, 0x2b,
	0x26, 0x0b, 0xc6, 0x24, 0x36, 0xb0, 0x13, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x7d,
	0x2c, 0x51, 0xb1, 0x00, 0x00, 0x00,
}
