// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbenc.proto

package enc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PBRequest is request of a RPC call encoded by protobuf.
type PBRequest struct {
	// Params is protobuf encoded params.
	Params []byte `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// Timeout sets an optinal timeout for this RPC.
	Timeout *duration.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Passthru is an optional dict carrying context values.
	Passthru             map[string]string `protobuf:"bytes,3,rep,name=passthru,proto3" json:"passthru,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PBRequest) Reset()         { *m = PBRequest{} }
func (m *PBRequest) String() string { return proto.CompactTextString(m) }
func (*PBRequest) ProtoMessage()    {}
func (*PBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbenc_5a5f3955dfeaf19b, []int{0}
}
func (m *PBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBRequest.Unmarshal(m, b)
}
func (m *PBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBRequest.Marshal(b, m, deterministic)
}
func (dst *PBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBRequest.Merge(dst, src)
}
func (m *PBRequest) XXX_Size() int {
	return xxx_messageInfo_PBRequest.Size(m)
}
func (m *PBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PBRequest proto.InternalMessageInfo

func (m *PBRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PBRequest) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *PBRequest) GetPassthru() map[string]string {
	if m != nil {
		return m.Passthru
	}
	return nil
}

// PBReply is reply of a RPC call encoded by protobuf.
type PBReply struct {
	// Types that are valid to be assigned to Reply:
	//	*PBReply_Result
	//	*PBReply_Error
	Reply                isPBReply_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBReply) Reset()         { *m = PBReply{} }
func (m *PBReply) String() string { return proto.CompactTextString(m) }
func (*PBReply) ProtoMessage()    {}
func (*PBReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbenc_5a5f3955dfeaf19b, []int{1}
}
func (m *PBReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBReply.Unmarshal(m, b)
}
func (m *PBReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBReply.Marshal(b, m, deterministic)
}
func (dst *PBReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBReply.Merge(dst, src)
}
func (m *PBReply) XXX_Size() int {
	return xxx_messageInfo_PBReply.Size(m)
}
func (m *PBReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PBReply.DiscardUnknown(m)
}

var xxx_messageInfo_PBReply proto.InternalMessageInfo

type isPBReply_Reply interface {
	isPBReply_Reply()
}

type PBReply_Result struct {
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}
type PBReply_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*PBReply_Result) isPBReply_Reply() {}
func (*PBReply_Error) isPBReply_Reply()  {}

func (m *PBReply) GetReply() isPBReply_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *PBReply) GetResult() []byte {
	if x, ok := m.GetReply().(*PBReply_Result); ok {
		return x.Result
	}
	return nil
}

func (m *PBReply) GetError() string {
	if x, ok := m.GetReply().(*PBReply_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PBReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PBReply_OneofMarshaler, _PBReply_OneofUnmarshaler, _PBReply_OneofSizer, []interface{}{
		(*PBReply_Result)(nil),
		(*PBReply_Error)(nil),
	}
}

func _PBReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PBReply)
	// reply
	switch x := m.Reply.(type) {
	case *PBReply_Result:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Result)
	case *PBReply_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("PBReply.Reply has unexpected type %T", x)
	}
	return nil
}

func _PBReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PBReply)
	switch tag {
	case 1: // reply.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Reply = &PBReply_Result{x}
		return true, err
	case 2: // reply.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reply = &PBReply_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _PBReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PBReply)
	// reply
	switch x := m.Reply.(type) {
	case *PBReply_Result:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Result)))
		n += len(x.Result)
	case *PBReply_Error:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*PBRequest)(nil), "enc.PBRequest")
	proto.RegisterMapType((map[string]string)(nil), "enc.PBRequest.PassthruEntry")
	proto.RegisterType((*PBReply)(nil), "enc.PBReply")
}

func init() { proto.RegisterFile("pbenc.proto", fileDescriptor_pbenc_5a5f3955dfeaf19b) }

var fileDescriptor_pbenc_5a5f3955dfeaf19b = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x97, 0x95, 0xb5, 0xf6, 0x56, 0x41, 0x82, 0x8c, 0x3a, 0x44, 0xca, 0x9e, 0xfa, 0x94,
	0xc1, 0xf6, 0x32, 0xf4, 0x6d, 0x4c, 0xd8, 0xe3, 0xc8, 0x3f, 0x48, 0xe7, 0x75, 0x0e, 0xbb, 0x26,
	0xde, 0x24, 0x42, 0x7f, 0xa5, 0x7f, 0x49, 0xda, 0x74, 0x03, 0xdf, 0xf2, 0xe5, 0x9e, 0x7b, 0xee,
	0x39, 0x90, 0x99, 0x0a, 0x9b, 0x83, 0x30, 0xa4, 0x9d, 0xe6, 0x11, 0x36, 0x87, 0xd9, 0xf3, 0x51,
	0xeb, 0x63, 0x8d, 0x8b, 0xfe, 0xab, 0xf2, 0x1f, 0x8b, 0x77, 0x4f, 0xca, 0x9d, 0x74, 0x13, 0x44,
	0xf3, 0x5f, 0x06, 0xe9, 0x7e, 0x23, 0xf1, 0xdb, 0xa3, 0x75, 0x7c, 0x0a, 0xb1, 0x51, 0xa4, 0xce,
	0x36, 0x67, 0x05, 0x2b, 0x6f, 0xe5, 0x40, 0x7c, 0x05, 0x89, 0x3b, 0x9d, 0x51, 0x7b, 0x97, 0x8f,
	0x0b, 0x56, 0x66, 0xcb, 0x47, 0x11, 0x7c, 0xc5, 0xc5, 0x57, 0x6c, 0x07, 0x5f, 0x79, 0x51, 0xf2,
	0x35, 0xdc, 0x18, 0x65, 0xad, 0xfb, 0x24, 0x9f, 0x47, 0x45, 0x54, 0x66, 0xcb, 0x27, 0xd1, 0xa5,
	0xbb, 0x9e, 0x13, 0xfb, 0x61, 0xfc, 0xd6, 0x38, 0x6a, 0xe5, 0x55, 0x3d, 0x7b, 0x85, 0xbb, 0x7f,
	0x23, 0x7e, 0x0f, 0xd1, 0x17, 0xb6, 0x7d, 0xa8, 0x54, 0x76, 0x4f, 0xfe, 0x00, 0x93, 0x1f, 0x55,
	0x7b, 0xec, 0xf3, 0xa4, 0x32, 0xc0, 0xcb, 0x78, 0xcd, 0xe6, 0x5b, 0x48, 0xba, 0x0b, 0xa6, 0x6e,
	0x79, 0x0e, 0x31, 0xa1, 0xf5, 0xb5, 0x0b, 0x75, 0x76, 0x23, 0x39, 0x30, 0x9f, 0xc2, 0x04, 0x89,
	0x34, 0x85, 0xf5, 0xdd, 0x48, 0x06, 0xdc, 0x24, 0x30, 0xa1, 0x6e, 0xb5, 0x8a, 0xfb, 0x62, 0xab,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x85, 0xd0, 0xb2, 0x52, 0x01, 0x00, 0x00,
}
