// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.7.1
// source: natsrpc.proto

package nppbnatsrpc

import (
	proto "github.com/golang/protobuf/proto"
	enc "github.com/huangjunwen/nproto/v2/pb/enc"
	md "github.com/huangjunwen/nproto/v2/pb/md"
	rpc "github.com/huangjunwen/nproto/v2/pb/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Request is natsrpc request wire format.
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MetaData dict.
	MetaData *md.MD `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// Input parameter.
	Input *enc.RawData `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Timeout optional timeout in nanoseoncds.
	Timeout uint64 `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_natsrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_natsrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_natsrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMetaData() *md.MD {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Request) GetInput() *enc.RawData {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Request) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// Response is natsrpc response wire format.
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Out:
	//	*Response_Output
	//	*Response_RpcErr
	//	*Response_Err
	Out isResponse_Out `protobuf_oneof:"out"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_natsrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_natsrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_natsrpc_proto_rawDescGZIP(), []int{1}
}

func (m *Response) GetOut() isResponse_Out {
	if m != nil {
		return m.Out
	}
	return nil
}

func (x *Response) GetOutput() *enc.RawData {
	if x, ok := x.GetOut().(*Response_Output); ok {
		return x.Output
	}
	return nil
}

func (x *Response) GetRpcErr() *rpc.RPCError {
	if x, ok := x.GetOut().(*Response_RpcErr); ok {
		return x.RpcErr
	}
	return nil
}

func (x *Response) GetErr() string {
	if x, ok := x.GetOut().(*Response_Err); ok {
		return x.Err
	}
	return ""
}

type isResponse_Out interface {
	isResponse_Out()
}

type Response_Output struct {
	// Output parameter when no error.
	Output *enc.RawData `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type Response_RpcErr struct {
	// RpcErr when rpc.RPCError returned.
	RpcErr *rpc.RPCError `protobuf:"bytes,2,opt,name=rpc_err,json=rpcErr,proto3,oneof"`
}

type Response_Err struct {
	// Err when other plain error returned.
	Err string `protobuf:"bytes,3,opt,name=err,proto3,oneof"`
}

func (*Response_Output) isResponse_Out() {}

func (*Response_RpcErr) isResponse_Out() {}

func (*Response_Err) isResponse_Out() {}

var File_natsrpc_proto protoreflect.FileDescriptor

var file_natsrpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x61, 0x74, 0x73, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x2e, 0x6e, 0x61, 0x74, 0x73, 0x72,
	0x70, 0x63, 0x1a, 0x0b, 0x6d, 0x64, 0x2f, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x65, 0x6e, 0x63, 0x2f, 0x65, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d,
	0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x64, 0x2e, 0x4d, 0x44, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x62, 0x2e, 0x65, 0x6e, 0x63, 0x2e, 0x52, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x22, 0x8b, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x2e, 0x65, 0x6e, 0x63, 0x2e, 0x52, 0x61,
	0x77, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x32, 0x0a, 0x07, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x50, 0x43, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x06, 0x72, 0x70, 0x63,
	0x45, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x42, 0x39,
	0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75, 0x61,
	0x6e, 0x67, 0x6a, 0x75, 0x6e, 0x77, 0x65, 0x6e, 0x2f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x32, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x61, 0x74, 0x73, 0x72, 0x70, 0x63, 0x3b, 0x6e, 0x70,
	0x70, 0x62, 0x6e, 0x61, 0x74, 0x73, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_natsrpc_proto_rawDescOnce sync.Once
	file_natsrpc_proto_rawDescData = file_natsrpc_proto_rawDesc
)

func file_natsrpc_proto_rawDescGZIP() []byte {
	file_natsrpc_proto_rawDescOnce.Do(func() {
		file_natsrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_natsrpc_proto_rawDescData)
	})
	return file_natsrpc_proto_rawDescData
}

var file_natsrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_natsrpc_proto_goTypes = []interface{}{
	(*Request)(nil),      // 0: nproto.pb.natsrpc.Request
	(*Response)(nil),     // 1: nproto.pb.natsrpc.Response
	(*md.MD)(nil),        // 2: nproto.pb.md.MD
	(*enc.RawData)(nil),  // 3: nproto.pb.enc.RawData
	(*rpc.RPCError)(nil), // 4: nproto.pb.rpc.RPCError
}
var file_natsrpc_proto_depIdxs = []int32{
	2, // 0: nproto.pb.natsrpc.Request.meta_data:type_name -> nproto.pb.md.MD
	3, // 1: nproto.pb.natsrpc.Request.input:type_name -> nproto.pb.enc.RawData
	3, // 2: nproto.pb.natsrpc.Response.output:type_name -> nproto.pb.enc.RawData
	4, // 3: nproto.pb.natsrpc.Response.rpc_err:type_name -> nproto.pb.rpc.RPCError
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_natsrpc_proto_init() }
func file_natsrpc_proto_init() {
	if File_natsrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_natsrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_natsrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_natsrpc_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Response_Output)(nil),
		(*Response_RpcErr)(nil),
		(*Response_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_natsrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_natsrpc_proto_goTypes,
		DependencyIndexes: file_natsrpc_proto_depIdxs,
		MessageInfos:      file_natsrpc_proto_msgTypes,
	}.Build()
	File_natsrpc_proto = out.File
	file_natsrpc_proto_rawDesc = nil
	file_natsrpc_proto_goTypes = nil
	file_natsrpc_proto_depIdxs = nil
}
