// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbenc.proto

package enc // import "github.com/huangjunwen/nproto/nproto/npmsg/enc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PBPayload is the MsgPayload encoded by protobuf.
type PBPayload struct {
	// MsgData is serialized message data.
	MsgData []byte `protobuf:"bytes,1,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	// MetaData dict. NOTE: map value can't be repeated type
	// See: https://stackoverflow.com/questions/38886789/protobuf3-how-to-describe-map-of-repeated-string
	MetaData             []*MetaDataKV `protobuf:"bytes,2,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PBPayload) Reset()         { *m = PBPayload{} }
func (m *PBPayload) String() string { return proto.CompactTextString(m) }
func (*PBPayload) ProtoMessage()    {}
func (*PBPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbenc_f6fd80b46c1c1a54, []int{0}
}
func (m *PBPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBPayload.Unmarshal(m, b)
}
func (m *PBPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBPayload.Marshal(b, m, deterministic)
}
func (dst *PBPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBPayload.Merge(dst, src)
}
func (m *PBPayload) XXX_Size() int {
	return xxx_messageInfo_PBPayload.Size(m)
}
func (m *PBPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PBPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PBPayload proto.InternalMessageInfo

func (m *PBPayload) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *PBPayload) GetMetaData() []*MetaDataKV {
	if m != nil {
		return m.MetaData
	}
	return nil
}

// MetaDataKV is a kv pair of meta data.
type MetaDataKV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaDataKV) Reset()         { *m = MetaDataKV{} }
func (m *MetaDataKV) String() string { return proto.CompactTextString(m) }
func (*MetaDataKV) ProtoMessage()    {}
func (*MetaDataKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbenc_f6fd80b46c1c1a54, []int{1}
}
func (m *MetaDataKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDataKV.Unmarshal(m, b)
}
func (m *MetaDataKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDataKV.Marshal(b, m, deterministic)
}
func (dst *MetaDataKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDataKV.Merge(dst, src)
}
func (m *MetaDataKV) XXX_Size() int {
	return xxx_messageInfo_MetaDataKV.Size(m)
}
func (m *MetaDataKV) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDataKV.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDataKV proto.InternalMessageInfo

func (m *MetaDataKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetaDataKV) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*PBPayload)(nil), "huangjunwen.nproto.npmsg.enc.PBPayload")
	proto.RegisterType((*MetaDataKV)(nil), "huangjunwen.nproto.npmsg.enc.MetaDataKV")
}

func init() { proto.RegisterFile("pbenc.proto", fileDescriptor_pbenc_f6fd80b46c1c1a54) }

var fileDescriptor_pbenc_f6fd80b46c1c1a54 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0x4a, 0xcd,
	0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xc9, 0x28, 0x4d, 0xcc, 0x4b, 0xcf, 0x2a,
	0xcd, 0x2b, 0x4f, 0xcd, 0xd3, 0xcb, 0x03, 0x8b, 0xe9, 0xe5, 0x15, 0xe4, 0x16, 0xa7, 0xeb, 0xa5,
	0xe6, 0x25, 0x2b, 0xe5, 0x72, 0x71, 0x06, 0x38, 0x05, 0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x08,
	0x49, 0x72, 0x71, 0xe4, 0x16, 0xa7, 0xc7, 0xa7, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x04, 0xb1, 0xe7, 0x16, 0xa7, 0xbb, 0x24, 0x96, 0x24, 0x0a, 0xb9, 0x72, 0x71, 0xe6, 0xa6,
	0x96, 0x24, 0x42, 0xe4, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x34, 0xf4, 0xf0, 0x99, 0xac, 0xe7,
	0x9b, 0x5a, 0x92, 0x08, 0xd2, 0xea, 0x1d, 0x16, 0xc4, 0x91, 0x0b, 0x65, 0x2b, 0x99, 0x71, 0x71,
	0x21, 0xc4, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xc1, 0x56, 0x71, 0x06, 0x81, 0x98, 0x42,
	0x62, 0x5c, 0x6c, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0xc5, 0x60, 0x3b, 0x38, 0x83, 0xa0, 0x3c, 0x27,
	0x83, 0x28, 0xbd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x24, 0x7b,
	0xf5, 0x21, 0xf6, 0x22, 0xa8, 0xdc, 0xe2, 0x74, 0xfd, 0xd4, 0xbc, 0xe4, 0x24, 0x36, 0xb0, 0x80,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x6a, 0x49, 0xd9, 0x0c, 0x01, 0x00, 0x00,
}
