// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package mathapi // import "github.com/huangjunwen/nproto/tests/math/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	Args                 []float64 `protobuf:"fixed64,1,rep,packed,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_59567345c2243e1f, []int{0}
}
func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (dst *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(dst, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetArgs() []float64 {
	if m != nil {
		return m.Args
	}
	return nil
}

type SumReply struct {
	Sum                  float64  `protobuf:"fixed64,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumReply) Reset()         { *m = SumReply{} }
func (m *SumReply) String() string { return proto.CompactTextString(m) }
func (*SumReply) ProtoMessage()    {}
func (*SumReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_59567345c2243e1f, []int{1}
}
func (m *SumReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumReply.Unmarshal(m, b)
}
func (m *SumReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumReply.Marshal(b, m, deterministic)
}
func (dst *SumReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumReply.Merge(dst, src)
}
func (m *SumReply) XXX_Size() int {
	return xxx_messageInfo_SumReply.Size(m)
}
func (m *SumReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SumReply.DiscardUnknown(m)
}

var xxx_messageInfo_SumReply proto.InternalMessageInfo

func (m *SumReply) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "math.SumRequest")
	proto.RegisterType((*SumReply)(nil), "math.SumReply")
}

func init() { proto.RegisterFile("math.proto", fileDescriptor_math_59567345c2243e1f) }

var fileDescriptor_math_59567345c2243e1f = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0x3d, 0xcb, 0xc2, 0x30,
	0x10, 0x07, 0x70, 0x42, 0xcb, 0xc3, 0xc3, 0x0d, 0x52, 0x32, 0x15, 0x71, 0x28, 0x5d, 0xec, 0xd4,
	0x80, 0x8a, 0x8b, 0x9b, 0xbb, 0x4b, 0xbb, 0xb9, 0xa5, 0x12, 0x9a, 0x4a, 0xf3, 0x62, 0x73, 0x87,
	0xf4, 0xdb, 0x4b, 0xb2, 0xe8, 0xf6, 0xe3, 0x5e, 0xff, 0x00, 0x46, 0xa2, 0x6e, 0xfd, 0xe2, 0xd0,
	0xf1, 0x3c, 0xba, 0xae, 0x00, 0x7a, 0x32, 0x9d, 0x7a, 0x91, 0x0a, 0xc8, 0x39, 0xe4, 0x72, 0x19,
	0x43, 0xc9, 0xaa, 0xac, 0x61, 0x5d, 0x72, 0xbd, 0x83, 0xff, 0x34, 0xe1, 0xe7, 0x95, 0x17, 0x90,
	0x05, 0x32, 0x25, 0xab, 0x58, 0xc3, 0xba, 0xc8, 0x83, 0x80, 0xfc, 0x26, 0x51, 0xf3, 0x3d, 0x64,
	0x3d, 0x19, 0x5e, 0xb4, 0xe9, 0xc3, 0xf7, 0xe4, 0x76, 0xf3, 0x53, 0xf1, 0xf3, 0x7a, 0x3d, 0xdf,
	0x4f, 0xe3, 0x84, 0x9a, 0x86, 0xf6, 0xe1, 0x8c, 0xd0, 0x24, 0xed, 0xf8, 0x24, 0xfb, 0x56, 0x56,
	0xd8, 0x94, 0x4b, 0xa0, 0x0a, 0x18, 0x44, 0x5c, 0x12, 0xd2, 0x4f, 0x97, 0x08, 0xe9, 0xa7, 0xe1,
	0x2f, 0x75, 0x8f, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x19, 0x69, 0x4c, 0xc3, 0x00, 0x00,
	0x00,
}
