// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RPCRequest is request of a RPC call.
type RPCRequest struct {
	// Params of the RPC.
	Params []byte `protobuf:"bytes,1,opt,name=Params,proto3" json:"Params,omitempty"`
	// Timeout sets an optinal timeout for this RPC.
	Timeout *duration.Duration `protobuf:"bytes,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	// Passthru is an optional dict carrying context values.
	Passthru             map[string]string `protobuf:"bytes,3,rep,name=Passthru,proto3" json:"Passthru,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_83258d1d665553d7, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (dst *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(dst, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

func (m *RPCRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RPCRequest) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *RPCRequest) GetPassthru() map[string]string {
	if m != nil {
		return m.Passthru
	}
	return nil
}

// RPCErrorReply is error reply of a RPC call. Similar to jsonrpc.
type RPCErrorReply struct {
	// Code is the error code.
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// Message is the error description.
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCErrorReply) Reset()         { *m = RPCErrorReply{} }
func (m *RPCErrorReply) String() string { return proto.CompactTextString(m) }
func (*RPCErrorReply) ProtoMessage()    {}
func (*RPCErrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_83258d1d665553d7, []int{1}
}
func (m *RPCErrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCErrorReply.Unmarshal(m, b)
}
func (m *RPCErrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCErrorReply.Marshal(b, m, deterministic)
}
func (dst *RPCErrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCErrorReply.Merge(dst, src)
}
func (m *RPCErrorReply) XXX_Size() int {
	return xxx_messageInfo_RPCErrorReply.Size(m)
}
func (m *RPCErrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCErrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_RPCErrorReply proto.InternalMessageInfo

func (m *RPCErrorReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RPCErrorReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// RPCReply is reply of a RPC call.
type RPCReply struct {
	// Result is the normal reply of the RPC. Must not set when there is an error.
	Result []byte `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	// Error is the error reply of the RPC. Must not set when there is no error.
	Error                *RPCErrorReply `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RPCReply) Reset()         { *m = RPCReply{} }
func (m *RPCReply) String() string { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()    {}
func (*RPCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_83258d1d665553d7, []int{2}
}
func (m *RPCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCReply.Unmarshal(m, b)
}
func (m *RPCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCReply.Marshal(b, m, deterministic)
}
func (dst *RPCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCReply.Merge(dst, src)
}
func (m *RPCReply) XXX_Size() int {
	return xxx_messageInfo_RPCReply.Size(m)
}
func (m *RPCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCReply.DiscardUnknown(m)
}

var xxx_messageInfo_RPCReply proto.InternalMessageInfo

func (m *RPCReply) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RPCReply) GetError() *RPCErrorReply {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "pb.RPCRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.RPCRequest.PassthruEntry")
	proto.RegisterType((*RPCErrorReply)(nil), "pb.RPCErrorReply")
	proto.RegisterType((*RPCReply)(nil), "pb.RPCReply")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_83258d1d665553d7) }

var fileDescriptor_rpc_83258d1d665553d7 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x89, 0x49, 0x9b, 0x57, 0x0b, 0xba, 0x48, 0x89, 0x45, 0x24, 0xe4, 0x62, 0x4e, 0x5b,
	0x68, 0x2f, 0x45, 0xf1, 0x14, 0x7b, 0x12, 0x21, 0x3c, 0xfc, 0x03, 0x1b, 0xbb, 0xc6, 0x62, 0xda,
	0x8d, 0xfb, 0x21, 0xe4, 0x5f, 0xfa, 0x93, 0xa4, 0x9b, 0xac, 0xc5, 0xdb, 0x9b, 0x9d, 0x79, 0xf3,
	0x66, 0x07, 0x62, 0xd9, 0xbe, 0xd1, 0x56, 0x0a, 0x2d, 0x88, 0xdf, 0x56, 0xf3, 0xdb, 0x5a, 0x88,
	0xba, 0xe1, 0x0b, 0xfb, 0x52, 0x99, 0xf7, 0xc5, 0xd6, 0x48, 0xa6, 0x77, 0xe2, 0xd0, 0x6b, 0xb2,
	0x1f, 0x0f, 0x00, 0xcb, 0x02, 0xf9, 0x97, 0xe1, 0x4a, 0x93, 0x19, 0x44, 0x25, 0x93, 0x6c, 0xaf,
	0x12, 0x2f, 0xf5, 0xf2, 0x73, 0x1c, 0x10, 0x59, 0xc1, 0xe8, 0x75, 0xb7, 0xe7, 0xc2, 0xe8, 0xc4,
	0x4f, 0xbd, 0x7c, 0xb2, 0xbc, 0xa6, 0xbd, 0x31, 0x75, 0xc6, 0xf4, 0x69, 0x30, 0x46, 0xa7, 0x24,
	0x6b, 0x18, 0x97, 0x4c, 0x29, 0xfd, 0x21, 0x4d, 0x12, 0xa4, 0x41, 0x3e, 0x59, 0xde, 0xd0, 0xb6,
	0xa2, 0xa7, 0x73, 0xd4, 0xd1, 0x9b, 0x83, 0x96, 0x1d, 0xfe, 0xa9, 0xe7, 0x0f, 0x30, 0xfd, 0x47,
	0x91, 0x0b, 0x08, 0x3e, 0x79, 0x67, 0x43, 0xc5, 0x78, 0x1c, 0xc9, 0x15, 0x84, 0xdf, 0xac, 0x31,
	0xdc, 0xe6, 0x89, 0xb1, 0x07, 0xf7, 0xfe, 0xda, 0xcb, 0x1e, 0x61, 0x8a, 0x65, 0xb1, 0x91, 0x52,
	0x48, 0xe4, 0x6d, 0xd3, 0x11, 0x02, 0x67, 0x85, 0xd8, 0x72, 0xbb, 0x1d, 0xa2, 0x9d, 0x49, 0x02,
	0xa3, 0x17, 0xae, 0x14, 0xab, 0x9d, 0x81, 0x83, 0xd9, 0x33, 0x8c, 0x6d, 0xc2, 0xe3, 0xe6, 0x0c,
	0x22, 0xe4, 0xca, 0x34, 0xda, 0xd5, 0xd1, 0x23, 0x72, 0x07, 0xa1, 0xf5, 0x1f, 0xca, 0xb8, 0x1c,
	0xbe, 0x75, 0xba, 0x89, 0x3d, 0x5f, 0x45, 0xb6, 0x9e, 0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0xfe, 0x9a, 0x2a, 0x96, 0x01, 0x00, 0x00,
}
